# Generated by Django 4.0.5 on 2022-06-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('add_date', models.DateTimeField(verbose_name='Add Date')),
            ],
        ),
        migrations.CreateModel(
            name='novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=250)),
                ('push_date', models.DateTimeField(verbose_name='Publish Date')),
                ('last_edit_date', models.DateTimeField(verbose_name='Last Edited')),
                ('total_chapters', models.IntegerField(default=0)),
            ],
        ),
    ]
