# Generated by Django 4.0.5 on 2022-06-28 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='novel',
            name='last_edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Edited'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='push_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Date'),
        ),
    ]
