# Generated by Django 4.0.5 on 2022-07-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_novel_description_alter_novel_last_edit_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='chapter',
        ),
        migrations.DeleteModel(
            name='novel',
        ),
    ]
